name: mix test

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
    branches:
      - master
      - dev/*
  pull_request:
    branches:
      - master

jobs:
  # Refactoring duplicated yaml is currently not possible
  # because Github does not support anchor syntax (& and *) now.
  elixir_1_12:
    runs-on: ubuntu-latest
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.12.0]
        otp: [24.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
  elixir_1_11:
    runs-on: ubuntu-latest
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.11.0]
        otp: [23.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
